name: pinapp_challenge
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  go_router: ^14.8.1
  intl: ^0.19.0
  meta: ^1.16.0
  posts_repository:
    path: packages/posts_repository

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

dependency_overrides:
  analyzer: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
