name: posts_repository
description: A Package that provides a repository for posts.
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  freezed: ^2.5.8
  http: ^1.3.0
  json_serializable: ^6.9.4

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
